# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Heimdall
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Documentation about the informatics project speechassisstents in summerterm 2020 at the university of applied science cologne
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.20.2"
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: [vendor]
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
github: [metadata]

# minimal-mistakes settings
minimal_mistakes_skin: "dark"

breadcrumbs: true
name: "Finn Wehn, Joost Groot Bramel"
repository: "th-koeln-intia/ip-sprachassistent-team2"
search: true
search_provider: algolia

algolia:
  application_id: 86SOZ7ZM65
  index_name: documentation
  search_only_api_key: be2af57a7e1b67e57236b127482475aa
  powered_by: true # true is requiered for the free plan of algolia

#include:
#  - *.md

# Add teaser image
# teaser: /assets/images/500x300.png
